---
- name: get vmdb object 
  hosts: localhost
  connection: local
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-automate

  tasks:
    - name: "Set the job ID back into $evm.root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "tower_job_id"
          value:  "{{ tower_job_id }}"

    # - name: "Get the full list of Objects"
    #   manageiq_automate:
    #     workspace: "{{ workspace }}"
    #     get_object_names: yes


    - name: "Get the full list of Object Attribute Names"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_object_attribute_names:
          object: "root"

    - name: Grab a vmdb object
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_vmdb_object:
          object: root
          attribute: service
      register: service_object

    - debug:
        msg: "{{ service_object }}"
