---
- name: get vmdb object 
  hosts: localhost
  connection: local
  
  vars:
    - auto_commit: true
    - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-automate

  tasks:
    - name: "Set the job ID back into $evm.root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "tower_job_id"
          value:  "{{ tower_job_id }}"

    - name: Grab a vmdb object
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_vmdb_object:
          object: root
          attribute: service_id
      register: id

    - debug:
        msg: "{{ id }}"
